### ISSUE TITLE
Add significant dates, zodiac and tide data to the CelestialInfo class

### ISSUE THREAD

**Issue by Tronald** [Tronald/CoordinateSharp#10]
For 1.1.1.6

Add nullable string to CelestialInfo that can identify if a significant day is occurring (i.e. equinox).

Add zodiac string to CelestialInfo that can identify current Zodiac according to current moon's ecliptic latitude and longitude (http://jivebay.com/calculating-the-moon-phase-part-2/).

Add Property to determine current tide data based on current position in the moon cycle.

**Comment by wider2** [comment]
in practical live, people like Moon due to some superstitious moments
and most of it they like Super Moon (perigee)
therefore significant dates could be different, not only equinox

**Comment by wider2** [comment]
In principle, we can add some named identifications of full moon, like '**Blue Moon**'
https://en.wikipedia.org/wiki/Blue_moon

it meaning the third full moon in a season of four full moons

**Comment by Tronald** [comment]
I have added this issue to the Celestial Details Feature Addition project. I am going to mark it closed, but it will remain in the project for reference during research of the features. 

Planned items to research and possibly add are:

Tidal Force Calculations
Lunar/Solar Eclipse Calculations
Moon Phase Detail Logic
Moon Sign (Zodiac) Calculations
Moon Name Identifiers (Blue Moon, Super Moon, Chinese New Year...etc).

Monitor the progress as I properties are added to identify significant events missed.
