### ISSUE TITLE
Rounding of coordinates in Coordinate.UTM

### ISSUE THREAD

**Issue by asherpatience1** [Tronald/CoordinateSharp#104]
**Describe the bug**
When getting a UniversalTransverseMercator from Coordinate.UTM, the expected output is truncated to 1 decimal place (1234.5)

**To Reproduce**
`
UniversalTransverseMercator utm = new Coordinate((double)-37.591443277331, (double)144.888483701251).UTM;
console.writeline(utm.Easting+", "+utm.Northing);
`

**Expected behavior**
Expected values:
utm.Easting - 313579.858262155, utm.Northing - 5837417.60084824
Resulting values:
utm.Easting - 313579.9, utm.Northing - 5837417.6

*NOTE* Casting to other data types reveals no extra decimal accuracy.

**Environment (please complete the following information):**
 - .NET version - 2.0 standard
 - CoordinateSharp version - 1.1.5.2
 - Desktop GIS software

**Additional context**
0.001m accuracy required during conversion.  To my knowledge the supplied lat/long values should yield better accuracy than the current 0.1m.

*EDIT*: Assuming, based on the resulting values, there may be a double->float->double conversion happening somewhere?

**Comment by Tronald** [comment]
Thank you for checking out CoordinateSharp.

Unfortunately this library isn't designed to support that level of precision in either it's coordinate conversions or celestial calculations. With that said the Easting and Northing values are rounded off by design in the conversion. You can fork the library and remove the rounding logic at the below lines here if you wish to test it out. I have no idea how precise it will be though. 

If you do it, get back to me and let me know how it works out!

https://github.com/Tronald/CoordinateSharp/blob/96ddc05ce7c3cf2fd3167a79d039fb62fc23311f/CoordinateSharp/UTM_MGRS/UTM.Methods.cs#L361

**Comment by asherpatience1** [comment]
> Thank you for checking out CoordinateSharp.
> 
> Unfortunately this library isn't designed to support that level of precision in either it's coordinate conversions or celestial calculations. With that said the Easting and Northing values are rounded off by design in the conversion. You can fork the library and remove the rounding logic at the below lines here if you wish to test it out. I have no idea how accurate it will be though.
> 
> If you do it, get back to me and let me know how it works out!
> 
> https://github.com/Tronald/CoordinateSharp/blob/96ddc05ce7c3cf2fd3167a79d039fb62fc23311f/CoordinateSharp/UTM_MGRS/UTM.Methods.cs#L361
> 
> https://github.com/Tronald/CoordinateSharp/blob/96ddc05ce7c3cf2fd3167a79d039fb62fc23311f/CoordinateSharp/UTM_MGRS/UTM.Methods.cs#L362

I made the suggested changed (locally on my machine) and here is the result of a UTM->DD->UTM conversion, without the rounding code.  First line is original input, second line is result after the two conversions.

313579.858262155, 5837417.60084824
313579.858257831, 5837417.60074786

With the larger element (northing), it is providing 0.0001m accuracy, which is perfect for this project.

This particular use-case is for converting and/or combining trajectory files from different inertial movement units (mobile laser scanning).

Thanks for your help by the way!

**Comment by Tronald** [comment]
Very cool usage thank you for sharing! And thanks for the feedback regarding the accuracy. 

I may look into changing the rounding rules, but I need to run some tests in the higher and lower parallels where the conversions start getting wonky to see how it acts. If I can consistently get 0.0001m of accuracy I don't see a reason to not modify the rounding rules. I am actually going to open this back up for tracking purposes.

Thanks again!

**Comment by Tronald** [comment]
Precision increased (UTM rounding rules removed) for v2.2.1.1 (Develop Branch). UTM Tests show passing, but increased precision accuracy relative to geodetic is still unknown. Use at your own risk.
