### ISSUE TITLE
[QUESTION]Does this plugin support converting from MGRS to Lat/Long?

### ISSUE THREAD

**Issue by VirtualJosh** [Tronald/CoordinateSharp#136]
I was looking at CoordinateSharp to solve a problem I need to support MGRS. My issue is that I need to convert a given MGRS coordinate into Lat/Long. Does this plugin support that functionality? I looked through the docs and couldn't find an answer. Thank you for your help regarding this.

**Comment by Tronald** [comment]
Thanks for checking out CoordinateSharp. This library certainly does what you need it too..

Have a look at our [Developer Guide](https://coordinatesharp.com/DeveloperGuide#universal-transverse-mercator-and-military-grid-reference-system).

If your MGRS coordinates are string format, you simply need to parse it out like in the example below. This example is UTM, but it works for MGRS.

```csharp
string s = "34X 551586mE 8921410mN"; //UTM Coordinate
Coordinate c; //Create new Coordindate to populate
if(Coordinate.TryParse(s, out c))
{
    //Coordinate parse was successful
    //Coordinate object has now been created and populated
    Console.WriteLine(c); //N 80º 20' 44.999" E 23º 45' 22.987"   
}
```

The `Coordinate` object will have all your lat/long values.

You can also pass specific values by building a `MilitaryGridReferenceSystem` object and then converting.

```csharp
var mgrs = new MilitaryGridReferenceSystem("17U", "PQ", 58747, 32983);
var coordinate = MilitaryGridReferenceSystem.MGRStoLatLong(mgrs);
Console.WriteLine(coordinate); //N 49º 1' 45.414" W 78º 49' 41.791"
Console.WriteLine(coordinate.Latitude.ToDouble()); //49.029281721258
```

Feel free to email support@signatgroup.com if you have any questions on using the library.
