### ISSUE TITLE
Wrong in calculating the Bearing

### ISSUE THREAD

**Issue by porya0ras** [Tronald/CoordinateSharp#137]
**Describe the bug**
When we give two points in the unit of UTM as these two points are below each other, it gives them an angle of 0.7, which is unacceptable.
At the same time, as this distance increases, so does this value
**To Reproduce**
```
UniversalTransverseMercator target_utm0 = new UniversalTransverseMercator("S", 38, 610001, 4213001);
Coordinate c0 = UniversalTransverseMercator.ConvertUTMtoLatLong(target_utm0);
UniversalTransverseMercator target_utm1 = new UniversalTransverseMercator("S", 38, 610001, 4215001);
Coordinate c1 = UniversalTransverseMercator.ConvertUTMtoLatLong(target_utm1);
Distance d = new Distance(c0, c1,Shape.Sphere);.
Console.WriteLine(d.Bearing);
```
**Expected behavior**
Then d.Bearing eqals 0.7 
:?

**Comment by Tronald** [comment]
Hi there, thank you for checking out CoordinateSharp.

Let me explain why this is happening.

As the earth is spherical, only the center of each UTM zone is facing **True North**. As you travel away from the center, **Grid North** will vary from **True North**. You can see this effect when you convert your UTM values into Geodetic.

* S38 610001 4213001 = N 38º 3.485' E 46º 15.232'
* S38 610001 4215001 = N 38º 4.566' E 46º 15.25'

As you can see, even though the UTM Northing value is the only change between coordinates, the "True North" value still changes when converting an angular Coordinate system like geodetic lat/long.

CoordinateSharp operates in angular values which will always give true values. It does not have the ability to operate in "constant distance relationship" as it's not designed to be used as that type of tool unfortunately.

The distance/bearing math is [explained well here](https://www.movable-type.co.uk/scripts/latlong.html).

If you need to maintain "map bearing" and not "true bearing" you will have to find another solution sadly. Sorry for any inconvenience, but I hope this helps clear it up.

-Justin
