### ISSUE TITLE
Strong name support

### ISSUE THREAD

**Issue by DanAvni** [Tronald/CoordinateSharp#139]
Please add a strong name to the project. I cannot reference it from a strong name using project as the project does not have a strong name

**Comment by Tronald** [comment]
Thanks for checking out CoordinateSharp.

I need to investigate how this should be handled. I'm worried about the side effects this would cause for existing users as well as the pains that will become introduced when people fork the library. I understand .NET Core has eased issues with binding redirects from strong naming that .NET Framework experiences, but a lot of people still use Framework (even though Microsoft likes to pretend everyone has switched to Core). With that said I don't pretend to be an expert on this subject and would like to research the best way to handle this.

I understand JsonNET only increments the assembly version for major builds to reduce issues. I also know some publishers have side-by-side versioned strong and weak named libraries. 

In the meantime, you should use [StrongNamer](https://www.nuget.org/packages/strongnamer). It's a Nuget package that will build your unsigned assemblies with strong names on build. It should allow you to use CoordinateSharp in it's current state.

**Comment by DanAvni** [comment]
On other projects I asked for it it was simply a matter of adding a sink file and telling the project to sign the assembly. AFAIK there is no impact on users who's assemblies are not signed but the opposite scenario where my assemblies are signed makes it impossible for me to use the unsigned assembly.

Another approach I saw one in FluentValidation had two packages: signed and unsigned. This was removed on version 7 and now the assembly is signed and the unsigned package is deprecated

**Comment by Tronald** [comment]
I totally understand your need for strong naming. After researching this a bit, I definitely do no want to have 2 forks of the assembly just to handle signing the assembly. 

I read up and saw the snk file inclusion solution you mentioned as well. As the purpose of the strong name is simply to create a unique identity and not security, I think I'm comfortable adding it to the assembly and including it in the fork. This way people may build there own forks as you mentioned.

I am going to increment to 2.6 and push an update with the strong named assembly tonight or tomorrow to Nuget. This update will change nothing other than adding the strong name. This way it can sit for a while and I can handle any binding redirect issues that come up from users while allowing them to revert to the previous version with no feature losses.

Will keep open until the 2.6 is published.

**Comment by Tronald** [comment]
[v2.6.1.1](https://www.nuget.org/packages/CoordinateSharp/2.6.1.1) was just published and adds the strong naming support you need.

Please let us know if it works out for you. 

Kind Regards!
