### ISSUE TITLE
Problem using the CoordinateSharp.Coordinate.Move method, going beyond provided point

### ISSUE THREAD

**Issue by Rakiah** [Tronald/CoordinateSharp#145]
Hello, I am using your system to run traffic simulation, basically I have simulated cars around a city that I assign routes to follow using [http://project-osrm.org/](osrm), OSRM will simply return a list of GPS coordinates that a simulated car has to follow to move from a point A to point B, I use the CoordinateSharp.Coordinate.Move() method to make my simulated cars move towards the next position in their routes so that they go from point A to point B smoothly

my problem is using this function it will sometimes move too "much" in a direction, resulting in the pathfinding system to recalculate the way, which makes them then move backwards.

**Expected behavior**
The Move method should be clamped and never go "beyond" the provided position

in the below case for example, currentCoordinate.Move may move beyond the nextCoordinate value, resulting in going too far away from the point and triggering a pathfinding recalculation
```
                        var distanceToMove = Math.Min(currentCoordinate.Get_Distance_From_Coordinate(nextCoordinate).Meters, Program.Configuration.Simulator.UnitsMetersPerSeconds);
                        metersToGo -= distanceToMove;

                        currentCoordinate.Move(nextCoordinate, new CoordinateSharp.Distance(distanceToMove, CoordinateSharp.DistanceType.Meters), CoordinateSharp.Shape.Ellipsoid);
```

**Environment (please complete the following information):**
 - .NET version.: .NET Core 3.1
 - CoordinateSharp version.: 2.4.1.1
 - Application type.: Console
 - Is mutlithreading being used?: No

**Comment by Tronald** [comment]
Thanks for checking out CoordinateSharp as well as reporting this issue.

1. Are you able to provide example values to plug into your example that will replicate the issue?
2. How far past the coordinate are you moving on average?

One thing I will note is that your `Get_Distance_From_Coordinate` call is using spherical calculations, while your `Move` call uses ellipsoidal. This could certainly cause the issues you specify as the distance math will not match between the two calls. I am hesitant to say that is definitely the issue though as it looks like your distances moved may be short. This issue would be show more with longer distances.

Change:

`currentCoordinate.Get_Distance_From_Coordinate(nextCoordinate)`

To

`currentCoordinate.Get_Distance_From_Coordinate(nextCoordinate,  CoordinateSharp.Shape.Ellipsoid)`

Try with the change, and report back.

**Comment by Rakiah** [comment]
I tried your change and can't seem to reproduce the bug anymore,

I will close this as fixed, thank you very much !

**Comment by Tronald** [comment]
@Rakiah thank you for the follow up. Glad it appears to be working now. Reach out if you run into anymore issues!
