### ISSUE TITLE
Another project compilation issue

### ISSUE THREAD

**Issue by davidspala** [Tronald/CoordinateSharp#156]
Hi again, clean cloned project has this compile issue:
1) The project CoordinateSharp_Playground is missing "Properties\AssemblyInfo.cs". Just deleting from project will help.
2) The project CoordinateSharp_UnitTests has in additional file "CoordinateSharp_UnitTexts.cs". It is exactly the same file as "...UnitTest.cs". Possible some sort of rename error. Just deleting from project will help.
Regards, David.

**Comment by Tronald** [comment]
Thank you for point these out. Looks like some stuff may not have merged correctly. I will get these fixed with the next update. If you find anything else, please let us know!
