### ISSUE TITLE
Is it possible to convert from UTM coordinates to lat/long?

### ISSUE THREAD

**Issue by SkinnySackboy** [Tronald/CoordinateSharp#165]
Hi,

Is it possible to convert UTM easting/northing coordinates to geospatial latitude/longitude using this library?

Many thanks

**Comment by Tronald** [comment]
I am assuming you answered your own question based on the closing of this topic, but if you need assistance please reach out.

**Comment by SkinnySackboy** [comment]
I did indeed, many thanks, great library!
