### ISSUE TITLE
Calculate sun altitude and azimuth for sun position?

### ISSUE THREAD

**Issue by lasseklein** [Tronald/CoordinateSharp#17]
Thanks for a great piece of code. This is excellent. I have added a few requests that I think would make this library more complete. I hope you agree.

The sun's altitude and azimuth currently seem to be missing from the calculations.

**Comment by Tronald** [comment]
Sorry for the huge delayed response! 

For some reason my notifications were turned off for this project. I appreciate all the inputs. Other commitments have sadly reduced the amount of effort I can put into this project, but I have a nice lull coming up. I am going to leave your issues open for now, and close them as I am able to complete them.

I'll keep you posted.

**Comment by Tronald** [comment]
Added in 1.1.1.6.
