### ISSUE TITLE
Parsing UPS/UTM Coordinates Can Fail

### ISSUE THREAD

**Issue by B4rrCH** [Tronald/CoordinateSharp#175]
I have encountered another issue with parsing. ☹

**Describe the bug**
Parsing strings with (barely) polar UTM coordinates can fail.

**To Reproduce**
```csharp
Coordinate c1 = new Coordinate(-80.365975, -91.980899);
string utmString = c1.UTM.ToString();
// utmString = "A 928609mE 1962943mN"
Coordinate c2 = Coordinate.Parse(utmString);
double distance_m = c1.Get_Distance_From_Coordinate(c2).Meters;
Assert.AreEqual(expected: 0,
                actual: distance_m,
                delta: 2.0,
                $"{c1} is not close to {c2}");
```
Results in
```
Assert.AreEqual failed. Expected a difference no greater than <2> between expected value <0> and actual value <2126031.01428607>.
S 80º 21' 57.51" W 91º 58' 51.236" is not close to S 64º 55' 32.726" W 135º 0' 16.456"
```
When using MGRS instead, this works. Coordinates further south (e.g. S 81°) work as expected. `Coordinate.TryParse(utmString, out Coordinate c2)` also returns true and sets c2 to the same values as in the example.

**Expected behavior**
I would expect `c1` and `c2` to be close to each other.

**Environment (please complete the following information):**
 - .NET Framework 4.7.2
 - CoordinateSharp version 2.9.1.3
 - Application type. Test Project.
 - Is mutlithreading being used? No.

**Comment by Tronald** [comment]
Fixed with 2.9.3.1. 

This was an inconsistent Easting Northing length issue (very easy fix). Unit test updated with case.

Please try new package and report back (hopefully no issues): https://www.nuget.org/packages/CoordinateSharp/2.9.3.1

I greatly appreciate your strict scrutiny of the parser.

**Comment by B4rrCH** [comment]
This did fix the UPS parsing, but now I have issues with parsing UTM strings coming from Coordinates with small non-negative latitudes (0<= lat <= 0.9032 ).

```csharp
Coordinate c1 = new Coordinate(0.9032, 0);
string s = c1.UTM.ToString();
// s = "31N 166062mE 99968mN"
// with Latitude = 0.9035: "31N 166062mE 100001mN" and works fine
Coordinate c2 = Coordinate.Parse(s);
double distance_m = c1.Get_Distance_From_Coordinate(c2).Meters;
Assert.AreEqual(expected: 0,
                actual: distance_m,
                delta: 2.0,
                $"{c1} is not close to {c2}");
```

If you're interested, I started extending the CoordinateSharp tests with random Parse-ToString compatiblity tests in my personal time and can create a PR when I'm off work again.

**Comment by B4rrCH** [comment]
Additional info: after a bit more investigation, it seems that while `31N 166062mE 99968mN` has issues being parse, it works fine for `31N 166062mE 099968mN`.

**Comment by Tronald** [comment]
@B4rrCH  that would be fantastic. If you can PR to the develop branch that would be stellar. I'm pretty embarrassed by the issues that keep presenting in the UTM/MGRS parsers of late so it's clear we need to extend these tests a lot further. I'm going to prioritize reworking these.

**Comment by Tronald** [comment]
Side note I adjusted the UTM parse order to account for uneven Easting Northing. The Regex had priority which doesn't handle those well. Can you give it a shot? 

Still would love your test cases.

https://www.nuget.org/packages/CoordinateSharp/2.9.4.1

**Comment by B4rrCH** [comment]
2.9.4.1 passes my fuzzy tests. I issued a PR. I saw you have contributor's licence agreement and filled it out: where should I best submit that?

**Comment by Tronald** [comment]
Thanks for the feedback! Please send the CLA to support@signatgroup.com. I'll review the PR and merge once you send. Greatly appreciate the contribution to our tests.
