### ISSUE TITLE
Give the name of moon phase

### ISSUE THREAD

**Issue by wider2** [Tronald/CoordinateSharp#18]
By example, we can calculate and return name of moon phase, based on age (from 0 to 1)

private string MoonPhaseName(double age) {
            string phase = "";
            if (age >= 0.98)
            {
                phase = _localizer["TourNewMoon"].Value;
            }
            else if (age > 0.5 && age < 0.98)
            {
                phase = (int)Math.Ceiling((age - 0.5) * 30) + " " + _localizer["TourDateMoonSet"].Value;
            }
            else if (age > 0 && age < 0.49)
            {
                phase = (int)Math.Ceiling((age * 30)) + " " + _localizer["TourDateMoonRise"].Value;
            }
            else if (age >= 0.49 && age <= 0.5)
            {
                phase = _localizer["TourFullMoon"].Value;
            }
            return phase;
}

**Comment by Tronald** [comment]
Feature added to 1.1.1.6
