### ISSUE TITLE
Possible bug in Coordinate.TryParse method

### ISSUE THREAD

**Issue by oderon-sp** [Tronald/CoordinateSharp#181]
Hello,

method public static bool TryParse(string value, out Coordinate coordinate)is possibly not working properly after last update. 
I relied on return value of Coordinate.TryParse to find out if user typed in a coordinate or a string with location name. Now when some non-location strings are passed coordinate.TryParse returns true. I.e. 'warszawa' or 'smart'. I singled out the following method as the culprit for your convinience.

https://github.com/Tronald/CoordinateSharp/blob/730b410be5a30c1c47afd5886dfd7cb803a9fca7/CoordinateSharp/Parsers/Coordinate%20Formats/MGRS.cs#L122

**Comment by Tronald** [comment]
Thank you for the bug report as well as the detailed description. 

The parser is taking the last 3 letters and forming what it thinks is the intended MGRS coordinate. So using "smart" it thinks you are parsing 0ART00. This is poor behavior though and its caused from the regex match not being required to match on the full string. 

I will get this fixed for you by the end of the day, and hopefully have it pushed out today or tomorrow.

**Comment by Tronald** [comment]
Fix pushed with [v2.9.5.1](https://github.com/Tronald/CoordinateSharp/releases/tag/v2.9.5.1). Package as been uploaded to [nuget](https://www.nuget.org/packages/CoordinateSharp/2.9.5.1).
