### ISSUE TITLE
Certificate error?

### ISSUE THREAD

**Issue by fnils** [Tronald/CoordinateSharp#192]
I get this when I try to go to the site. https://coordinatesharp.com/
It there an issue with the certificate or has it possibly been hacked?
 
![image](https://user-images.githubusercontent.com/20942566/134474831-d2dcc0d8-77f6-41dc-9ff4-51de353bf052.png)

**Comment by Tronald** [comment]
Hello,

I am unable to replicate the issue on my end using firefox. The certificate appears valid still as well (not expiring until November). Is it possibly an issue with your developer edition settings, firewall or anti-virus? The website does use javascript that requests location from the user, so it's possible strict settings are detecting and blocking that as well.

![image](https://user-images.githubusercontent.com/24424871/134530680-4fa6d029-978f-491d-b8f7-2ab0e4abe125.png)

**Comment by Tronald** [comment]
@sigvaldhoy thank you so much for the follow up and working that! I will go ahead an close the issue!
