### ISSUE TITLE
the example from the website for formatting coordinates as strings does not work as shown

### ISSUE THREAD

**Issue by KDOTBLP** [Tronald/CoordinateSharp#195]
**Describe the bug**
I am using LinqPad to test this extremely trivial example.  I encountered a problem.

This does not work:
     
```
    var gps_lat = "39.050934";
    var gps_lon = "-95.678382";
    var nbiLat  = "";
    var nbiLon = "";

        if (Double.TryParse(gps_lat, out var dblLat))
        {
	        nbiLat= LBIS_BrMUtils.GetNbiLatLongFromGps(dblLat, 0);
        
        }
        ((char)176).ToString().Dump();
        
        if (Double.TryParse(gps_lon, out var dblLon))
        {
	        nbiLon = LBIS_BrMUtils.GetNbiLatLongFromGps(dblLon, 0);
        
        }   
         Coordinate c = new Coordinate(40.57682, -70.75678);
        
            c.FormatOptions.CoordinateFormatType = CoordinateFormatType.Degree_Decimal_Minutes;
            c.FormatOptions.Display_Leading_Zeros = true;
            c.FormatOptions.Round = 3;
        
            c.ToString();           // N 40º 34.609' W 070º 045.407'
            c.Latitude.ToString();  // N 40º 34.609'
            c.Longitude.ToString(); // W 070º 45.407'
 
```

This does:

```
        var gps_lat = "39.050934";
        var gps_lon = "-95.678382";
        var nbiLat  = "";
        var nbiLon = "";
        
        if (Double.TryParse(gps_lat, out var dblLat))
        {
	        nbiLat= LBIS_BrMUtils.GetNbiLatLongFromGps(dblLat, 0);
        
        } 
        
        if (Double.TryParse(gps_lon, out var dblLon))
        {
	        nbiLon = LBIS_BrMUtils.GetNbiLatLongFromGps(dblLon, 0);
        
        }
        var c = new CoordinateSharp.Coordinate(dblLat, dblLon);
        // c.Dump()
        c.FormatOptions.Format =  CoordinateFormatType.Degree_Decimal_Minutes;
         
        c.ToString().Dump("Degree_Decimal_Minutes");
        
        c.FormatOptions.Format = CoordinateFormatType.Degree_Minutes_Seconds	;
        c.ToString().Dump("Degree_Minutes_Seconds");
```

**To Reproduce**

Use Linqpad or whatever, try to use this example.  The Type  FormatOptions.CoordinateFormatType does not exist?

**Expected behavior**
The coordinate would be formatted

**Environment (please complete the following information):**
.NET 4.8
CoordinateSharp 2.12.1.1

**Additional context**

**Comment by Tronald** [comment]
Thank you for bringing this to our attention.

It appears the Developer Guide for this example is just out of date. The `enum` name is `CoordinateFormatType` but the property name contained in the `CoordinateFormatOptions` object is named 'Format'. 

 It looks like you figured out that you need to use the `Format` property, but let me know if you have further questions. 
 
- Base documentation appears correct.
- Developer Guides needs to be updated.

INCORRECT: ` coordinate.FormatOptions.CoordinateFormatType = CoordinateFormatType.Degree_Decimal_Minutes;`
CORRECT: ` coordinate.FormatOptions.Format =  CoordinateFormatType.Degree_Decimal_Minutes;`

**Comment by Tronald** [comment]
Developer Guide Updated: https://coordinatesharp.com/DeveloperGuide#formatting-a-coordinate-output
