### ISSUE TITLE
Sunset/Sunrise times issue

### ISSUE THREAD

**Issue by arikadiusz** [Tronald/CoordinateSharp#198]
**Describe the bug**
Sunset and Sunrise times are one hour behind in GMT (UTC+1), library won't take day light saving under consideration.
I am testing to Reading, UK

**To Reproduce**
```csharp
        static void Main(string[] args)
        {
            Coordinate coordinates = new Coordinate(51.4551, 0.9787, DateTime.Now);

            Console.WriteLine($"DayLightSaving : {DateTime.Now.IsDaylightSavingTime()}");
            Console.WriteLine($"{DateTime.Now}");

            Console.WriteLine("Celestial Info");
            Console.WriteLine($"GeoDate = {coordinates.GeoDate}");
            Console.WriteLine($"Sunset = {coordinates.CelestialInfo.SunSet}");
            Console.WriteLine($"Sunrise = {coordinates.CelestialInfo.SunRise}");

            Console.ReadLine();
        }
```

output :
DayLightSaving : True
02/06/2022 18:36:04
Celestial Info
GeoDate = 02/06/2022 18:36:04
Sunset = 02/06/2022 20:05:20
Sunrise = 02/06/2022 03:45:40

**Expected behavior**
Sunrise and Sunset times to be correct. Currently both sunrise and sunset is 1h behind

**Environment (please complete the following information):**
 - .NET version. 4.7
 - CoordinateSharp version. 2.13.1.1
 - Application type. Console Application
 - Is mutlithreading being used? No

**Additional context**
N/A

**Comment by Tronald** [comment]
Hello,

CoordinateSharp operates in UTC time only, regardless of `DateTimeKind` per docs. So even though your `DateTime` object is local, CoordinateSharp treats it as UTC if an `offset` is not passed.

https://coordinatesharp.com/DeveloperGuide#accessing-celestial-data

If you plan to operate in local time, you must first extract and set the UTC offset.

Example from documentation:

```C#
//EST Date 21-MAR-2019 @ 07:00 AM
DateTime d = new DateTime(2017,3,21,7,0,0);
Coordinate c = new Coordinate(40.57682, -70.75678, d);

//Coordinate still assumes the date is UTC, so we must specify the local offset hours.
c.Offset = -4; //EST is UTC -4 hours

c.CelestialInfo.SunRise.ToString(); //Outputs 3/21/2017 06:45:00 AM
```

UTC Offset can be extracted from a DateTime object.

```C#DateTime utcDate = MyDate.ToUniversalTime();
TimeSpan ts = utcNow - now;
v
```
