### ISSUE TITLE
CoordinatePart.TryParse throws exception if value is out of range.

### ISSUE THREAD

**Issue by Donsroom** [Tronald/CoordinateSharp#205]
**Describe the bug**
CoordinatePart.TryParse throws and exception like the following if the provided value is out of range:

`System.ArgumentOutOfRangeException: 'Latitudinal coordinate decimal cannot be greater than 90. Value Provided = 330 (Parameter 'Degrees out of range')'
`

**To Reproduce**
The following code will throw the exception if the provided latitude value is out of range:

```
if (!CoordinatePart.TryParse(latitude, CoordinateType.Lat, out CoordinatePart latitudePart))
{
    return null;
}

```

**Expected behavior**
TryParse should not throw an exception but instead should return false.

**Environment (please complete the following information):**
 - .NET version: 6.0
 - CoordinateSharp version: 2.14.2.1

**Additional context**
If this is working as designed then please disregard this bug report.

**Comment by Tronald** [comment]
Hello There,

I am unable to replicate this issue. Please see the .NET 6 example here as it execute successfully: https://dotnetfiddle.net/edYyYT

This may be your compiler breaking on internal exceptions. These internal exceptions are absorbed by the `TryParse` method automatically, but sometimes compilers will break on them and ask if you want to continue execution. There is usually an option to ignore those exceptions when the break happens however.

Are you using Visual Studio?

**Comment by Donsroom** [comment]
Thank you so much for the response.

I am using Visual Studio, C#, .NET 6 and WinUI 3. And based on you not being able to reproduce the issue I have to assume the issue is on my side.

I will do further investigating on my side and check the things you mentioned. Once I have determined what the issue is I will report back here for the benefit of yourself and others.

**Comment by Donsroom** [comment]
This was, indeed, a mistake on my side. At some point I had enabled all of the exceptions in the Exception Settings window:
![2022-11-19_112011](https://user-images.githubusercontent.com/7144722/202863548-469a5d61-de37-49ee-8945-f965038331e3.jpg)

After clicking the "Restore the list to the default settings" button VS no longer breaks when the exception is thrown:
![2022-11-19_112056](https://user-images.githubusercontent.com/7144722/202863555-8e700914-4dcd-4329-83aa-62ce8436af6d.jpg)
My apologies for the false report. Thanks again and feel free to close this issue.

**Comment by Tronald** [comment]
Thanks for the update, and glad I could help. This circumstance catches me often on various random projects, so I kind of figured it was something along those lines.
