### ISSUE TITLE
Precision support for `ToRoundedString`

### ISSUE THREAD

**Issue by cervengoc** [Tronald/CoordinateSharp#208]
We'd like to display UTM in centimeter precision, which means 2 decimal digits. Right now the 5 decimal digit precision is hard-coded in `ToCentimeterString` method and the 0 digits is hard-coded in the `ToRoundedString` method.

I'd like to have an overload with a parameter where one can set the precision for the `ToRoundedString` method.

I've started working on a small PR for this.

**Comment by Tronald** [comment]
Thank you for the suggestion. I think it is a great. I will review you PR.
