### ISSUE TITLE
Use Enum for Zodiac sign and Moon name

### ISSUE THREAD

**Issue by alfamizar** [Tronald/CoordinateSharp#211]
Hello. 
Thank you for such great work with this cute lib.

I would ask you, if is it possible to change zodiac type from string to Enum type, as it more clean way to represent values enumeration and more bulletproof against typos. Most of the users are using this library for internationally translated apps and using a converter EnumToLocalizedString would be more straightforward to display Sign in UI.

Thanks for attention.

**Comment by Tronald** [comment]
Agreed, an enum option makes much more sense.

**Comment by Tronald** [comment]
Added with 2.16.1.1
