### ISSUE TITLE
Package available for Xamarin.iOS and MonoAndroid

### ISSUE THREAD

**Issue by andreasfromch** [Tronald/CoordinateSharp#22]
It would be great to have this great package available for Xamarin.iOS and MonoAndroid as well. Are there any plans to add this?

**Comment by Tronald** [comment]
I personally don't have any experience with Xamarin.iOS or MonoAndroid. I would love to learn how these work, but I have to prioritize my time. If anyone else has experience in this, I would certainly work with them to tackle this issue. 

I will add this feature to the enhancement list, but keep this open with a help wanted tag in case anyone wants to assist and take lead on this.

**Comment by APinheiroPT** [comment]
If you want, i can help.

**Comment by Tronald** [comment]
That would be awesome!!! Just let me know what you need from me or what I need to do. I have zero experience with this so I’ll let you take lead on this.

**Comment by Tronald** [comment]
@APinheiroPT any updates? If not this issue is still alive and well!

**Comment by Tronald** [comment]
Closing the issue and reopening with new/broader requirements.
