### ISSUE TITLE
[QUESTION] How to convert from arbitrary system to latitude, longitude?

### ISSUE THREAD

**Issue by macias** [Tronald/CoordinateSharp#220]
I am sorry for asking without more background knowledge about coordinate systems in general. Basically I have SHP data which I know are stored as "EPSG:2180 - ETRS89 / Poland CS92 - Projected" data (this info is from QGIS).

So when I read the geometry data in C#, I get such outcome:
```
SHAPE: MULTIPOLYGON (((771214.98 665105.63, 771172.26 665180.86, 771157.59 665219.24, 771113.83 665193.19, 771068.6 665281.53, 770955.27 665502.86, 771005.93 665474.92, 771018.35 665487.04, 771027.9 665480, 771037.92 665506.39, 771044.27 665511.74, 771042.6 665530.45, 771035.25 665539.8, 771040.26 665564.19, 771016.61 665598.58, 771000.5 665621.99, 770991.31 665649.22, 770997.43 665658.12, 771003.01 665666.26, 770999.33 665690.98, 770997.85 665713.04, 771113.41 665488.24, 771093.74 665467.12, 771062.78 665416.12, 771062.86 665385.38, 771094.91 665348.7, 771127.82 665332.99, 771132.11 665337.42, 771165.64 665329.35, 771238.63 665199.18, 771266.13 665150.48, 771214.98 665105.63)))
```

Now I would like to convert those data to regular latitude, longitude format. Is CoordinateSharp capable of doing such conversion? If yes, how to do it?

Thank you in advance for your help.

**Comment by Tronald** [comment]
Hi @macias 

Unfortunately CoordinateSharp does not have the current capability to convert to EPSG:2190. While we are always working on adding new coordinate systems, we tend to refrain from localized systems or systems requiring evolving data sets within the base library.

Sadly, there isn't a lot out there for .NET on this either. [epsg](https://epsg.org/crs_2180/ETRF2000-PL-CS92.html?) would be your best bet. The conversion details are listed on the site, although they are not necessarily easy to dive into. I will research this further when I have time as it would be nice to provide limited ability for conversion where users could plug in the conversion parameters on their own. Such a project will take time however.

Sorry I don't have better news.
