### ISSUE TITLE
lunar eclipse

### ISSUE THREAD

**Issue by wider2** [Tronald/CoordinateSharp#23]
31.01.2018 was the Total Lunar Eclipse

Is it possible to find algorithm of such and later eclipses and add it to the CoordinateSharp  application?

**Comment by Tronald** [comment]
I have looked into it and added it to my the Enhancement Request file in the repository. I couldn't tackle the issue in the last release as it was kind of involved. But I have algorithms for reference from [NASA](https://eclipse.gsfc.nasa.gov/eclipse.html). I am hoping I can tackle this sometime in March. I will keep you posted.

**Comment by Tronald** [comment]
Hey @wider2 I have an update for you.  I have successfully calculated Solar Eclipse data based on lat/longs. With that said I have quite a bit of clean up to do, as well as adding Lunar Eclipse data. Currently, the functionality is returning a `List<List<string>>` that can be iterated for 100 year eclipse data. I need to change how this works, but it's based off NASA's eclipse calculator and I wanted to successfully convert their javascript calculator before modifying it to much.

I will probably release a beta version of this with my next release. Sorry this is taking so long. It ended up being a bit more tedious then expected.

**Comment by Tronald** [comment]
I have implement this functionality and it will be released with the next update. I'm going to go ahead and close this. Thanks again for all your input.
