### ISSUE TITLE
Converting to/from Sweref 99

### ISSUE THREAD

**Issue by LinusNil** [Tronald/CoordinateSharp#234]
I am having a hard time figuring this out. How to I convert between WGS 84 and SWEREF 99 TM?
https://epsg.io/3006

I believe I should probably use UniversalTransverseMercator in some way but I am really stuck. Any help would be highly appreciated.

**Comment by Tronald** [comment]
Hi There. Unfortunately CoordinateSharp does not have the ability to convert to local level systems like SWEREF 99 TM. While SWEREF 99 is a 2D system, it is not the same as the world-wide UTM system. We are exploring an extension that would allow users to enter required parameters to self build conversion by the systems known transformation, but we are a ways away from that.

If the link below doesn't work you can search for "3006" in the search box on the left. That result will provide the math conversion formulas...but they've aren't exactly easy to follow.

https://epsg.org/crs_3006/SWEREF99-TM.html?sessionkey=moafl8bha7

Sorry I don't have better news at this time.
