### ISSUE TITLE
Can I change Datum to EuRef89

### ISSUE THREAD

**Issue by quoctiennguyen** [Tronald/CoordinateSharp#26]
As I know, default Datum using in CoordinateSharp is Wgs84
Can I update/change it to Euref89
Thanks

**Comment by Tronald** [comment]
As of this time users cannot change the datum, but this is something I have planned for and should be able to implement quickly. Is this for UTM conversions for Norway?

Just note: EUREF89 uses the GRS80 ellipsoid which is very close to WGS84, so you shouldn't see a huge difference. I will look into implementing this.

**Comment by Tronald** [comment]
Ok so, I just implemented the ability to pass custom datums by creating custom Equatorial Radius and Inverse Flattening properties. I need to test a bit more and update the documentation when I have time tomorrow, but I will try and push a Nuget Package for you by tomorrow evening (US EST time). 

I will post back in here with instructions based on your concerns before closing this issue.

**Comment by Tronald** [comment]
I just pushed 1.1.2.4 to nuget and it can do what you need. You have two options depending on what you need to accomplish. First is to create a Coordinate based on a known Lat/Long and then set the datum. Second is to create a UTM with a custom datum. Custom datums are built by setting the Equatorial Radius and Inverse Flattening values.

For EUREF89 those values are RADIUS: 6378137  FLATTENING: 298.225222101

Using Method 1 (if lat/long is known):

```C#
Coordinate  c = new Coordinate(59.9139, 10.7522); //Create a coordinate from Lat/Long
c.Set_Datum(6378137, 298.225222101);//Change the datum from WGS84 to custom value.
```

Using Method 2 (if UTM is known):

```C#
UniversalTransverseMercator utm = new UniversalTransverseMercator("Q", 14, 581943.5, 2111989.8, 6378137, 298.225222101);//Create a UTM object with a custom datum.
Coordinate c = UniversalTransverseMercator.ConvertUTMtoLatLong(utm); //Convert UTM to coordinate object.
```
Let me know if you have any questions, or run into any issues. The Nuget package may take a while to index so if you may not see it right away in the search results.
