### ISSUE TITLE
Should this not be "> 180" instead of "> 90"?

### ISSUE THREAD

**Issue by Professor-Periwinkle** [Tronald/CoordinateSharp#39]
https://github.com/Tronald/CoordinateSharp/blob/e696f984c60d9d09f1e0052f5d4c04b511539cfc/Coordinate.cs#L1086

**Comment by Tronald** [comment]
I just face-palmed myself for this.

What a stupid typo on my part. Good catch, thank you for bringing it to my attention! I will get that fixed.

**Comment by Professor-Periwinkle** [comment]
No problem xD

**Comment by Tronald** [comment]
I'm going to reopen until the update's pushed for tracking purposes.

**Comment by Professor-Periwinkle** [comment]
My bad sorry
Pressed the wrong button xD

**Comment by Tronald** [comment]
All good :)

**Comment by Tronald** [comment]
I was able to fix it and push an update to Nuget. Give it a minute to index if you don't see it right away. Thanks for bringing this to my attention again! Let me know if you have any more issues. 

Out of curiosity, what brought you to this library? I like seeing what people use it for so I know what areas to concentrate on when making improvements.
