### ISSUE TITLE
Logo Proposal for CoordinateSharp

### ISSUE THREAD

**Issue by area55git** [Tronald/CoordinateSharp#41]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project CoordinateSharp.

I will be pleased to collaborate with you.

**Comment by Tronald** [comment]
Thank you for reaching out.

Here is the current logo that I use for Nuget.

![CoordinateSharp Logo](https://raw.githubusercontent.com/Tronald/CoordinateSharp/master/ICON.png)

With that said I am not opposed to a better logo if you have some proposals.

**Comment by area55git** [comment]
Yes, I saw the Logo and I can improve it, have any suggestions or want to use some color?

**Comment by Tronald** [comment]
I have no preferences. Feel free to be as creative as you want. Thank you.

**Comment by area55git** [comment]
Perfect, in a couple of days I will send you some proposals.

**Comment by area55git** [comment]
Hi @Tronald I present you 2 logo proposals:

[![LOGO_PROPOSAL_FOR_COORDINATESHARP.jpg](https://s33.postimg.cc/56totr31b/LOGO_PROPOSAL_FOR_COORDINATESHARP.jpg)](https://postimg.cc/image/5wch643kr/)

What you think?
Remember that these are sketches and you can suggest any change.

**Comment by Tronald** [comment]
I really like the modern look of the second one! It's awesome. Would you be able to provide just the icon part in an .ico file as well? Really great work!

**Comment by Tronald** [comment]
Also, how would you like to be recognized for the design once its complete? I can link your name in the acknowledgements. I can put it on the [website](https://coordinatesharp.com) as well.

**Comment by area55git** [comment]
What color option do you like?
I also used several fonts to choose the one you like most

[![LOGO_PROPOSAL_FOR_COORDINATESHARP.jpg](https://s8.postimg.cc/xtjiri079/LOGO_PROPOSAL_FOR_COORDINATESHARP.jpg)](https://postimg.cc/image/x40qf4znl/)

**Comment by Tronald** [comment]
I like the blue icon best (blue sky’s/flight). I like the font under the red icon. Looks “techy”

**Comment by area55git** [comment]
perfect, I will make the changes. I'll send you the files in SVG and PNG

**Comment by area55git** [comment]
Hi @Tronald Which of these options would you like to merge?


[![LOGO_COORDINATE_SHARP.jpg](https://s8.postimg.cc/vqtcwakb9/LOGO_COORDINATE_SHARP.jpg)](https://postimg.cc/image/6810ja0r5/)

**Comment by area55git** [comment]
### [FILE DOWNLOAD](https://drive.google.com/open?id=1dMQ4XYu9oOnx8X88YTDWy3vxcFmP0ova)

[![DERECHOS.jpg](https://s8.postimg.cc/bamxri9md/DERECHOS.jpg)](https://postimg.cc/image/k5ns20yep/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
Thank you for accepting my contribution in your project.

Remember that I can collaborate with the design of logos in other projects, you can recommend my work.

**Comment by Tronald** [comment]
YESSSS!!! thank you!!!! These look so nice. 

Regarding the merge I like the second one (blue background). 

Thank you for providing me all the files so I have different options. Just so you know I’m in the process of moving my documentation over to the website, so I will be using the graphics there as well. I will certainly provide acknowledgement and recommendations for your work.

Thank you so much again it looks great!

**Comment by area55git** [comment]
PR #45

**Comment by Tronald** [comment]
@area55git I’m loving the new logos! Out of curiousity, could you send me a png [of this icon](https://coordinatesharp.com/favicon.ico) sized to 64x64. I’m just having issues scaling it myself. When I scale it distorts/blurs the image slightly.

Thanks again for your hard work!

**Comment by area55git** [comment]
Ready, the logos are in the previous link, I sent them to you in SVG, PNG, ICO in 64x64px
