### ISSUE TITLE
Add project and solution files?

### ISSUE THREAD

**Issue by dsherret** [Tronald/CoordinateSharp#48]
Hey, is there a reason the project and solution files are missing from the repo?

**Comment by Tronald** [comment]
Mainly just me being bad at GitHub. I added them.

**Comment by dsherret** [comment]
Great. Thanks for the quick fix!

**Comment by Tronald** [comment]
No problem! If you make any cool additions or find any bugs, be sure to let me know as I'm always trying to improve this library.

Thanks
