### ISSUE TITLE
Mars opposition

### ISSUE THREAD

**Issue by wider2** [Tronald/CoordinateSharp#53]
Today is the Great opposition of Mars

in principle, these days could be also included into the library

2018-07-27
2020-10-14
2022-12-08
2025-01-16
2027-02-19
2029-03-25
2018-07-31
2020-10-06
2022-12-01
2025-01-12
2027-02-20
2029-03-29

**Comment by Tronald** [comment]
I eventually want to expand to allow planetary properties. I've slowly been adding the previous properties we discussed (like perigee, zodiac, eclipse info, etc). Once, I'm happy with the accuracy, behavior and properties of my solar/lunar area. I will research expansion.

With that said opposition dates weren't even somethings I had considered. That will be a good property to add when the time comes. For now I'm going to leave the planetary stuff out as it would be too vague, but will reference this when I start research on that area.

Thanks as always @wider2
