### ISSUE TITLE
SunAltitude stopped working

### ISSUE THREAD

**Issue by dsherret** [Tronald/CoordinateSharp#58]
Hey, thanks for fixing the .net core warnings. Unfortunately the sun altitude calculation seems to have stopped working:

```ts
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 16, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 17, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 18, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 19, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 20, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 21, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 22, 0, 0)));
Debug.WriteLine(GetAltitude(new DateTime(2018, 8, 5, 23, 0, 0)));

double GetAltitude(DateTime dateTime)
{
    var coordinate = new Coordinate(43.653908, -79.384293, dateTime.ToUniversalTime());
    return coordinate.CelestialInfo.SunAltitude;
}
```

Outputs:

```
5.49222218568126
5.49222218568126
5.49222218568126
5.49222218568126
5.28696706518481
5.28696706518481
5.28696706518481
5.28696706518481
```

**Comment by Tronald** [comment]
@dsherret #^%$* Thanks! I found the issue immediately. I passed an incorrect value after I made adjustments to the solar time calculations. I'm fixing it now! I'll message back in a few when it's pushed.

**Comment by Tronald** [comment]
@dsherret It's pushed to GitHub, Nuget and the Website. I unlisted the versions effected by the issue. The only properties effected were sun alt/az. I had set the function that handles them to calculate the stripped `GeoDate` with no time by accident. 

Silly mistake. Thank you for bringing it to my attention, let me know if you find anything else. It should work now.

**Comment by dsherret** [comment]
Thanks for the quick fix and once again for the awesome project!

By the way, I highly recommend adding a test project to ensure the public api is returning values within a certain epsilon (working on it slowly with bug fixes is a good time to start). It will allow you to do changes with confidence and catch mistakes like this :)
