### ISSUE TITLE
Ellipsoid Height & Proper ECEF Functionality

### ISSUE THREAD

**Issue by joshmclean** [Tronald/CoordinateSharp#68]
Hi,

This is an excellent Nuget library.

I wanted to convert from ECEF X, Y, Z to Latitude, Longitude and Ellipsoid height (and vice visa)

I would have expected the resultant coord object to have ellipsoid height somewhere but I cannot find it, to my surprise.

var coord = CoordinateSharp.Cartesian.CartesianToLatLong(_x, _y, _z);

Am I missing something?

Thanks
Joshua

**Comment by joshmclean** [comment]
Hi,

Some time ago I created a very simple c# implementation of ECEF <> Geodetic coordinate conversion based on this document I found: http://clynchg3c.com/Technote/geodesy/coordcvt.pdf

It just requires the user to define the semi major and inverse flattening (or eccentricity) which your code provides.

Note - I did not fully implement GetHeight to account for near poles. So if you want to be complete, then you'd need to refer to the document.

Feel free to use this for your purpose. Don't take the solution as it is, do perform unit tests to ensure we get correct results at various locations around the earth which I'm sure you'll do anyway.


ECEF to Geodetic
 ```
class ECEFToGeodetic
        {
            const double SemiMajor = 6378137.0; //User-defined
            const double InverseFlattening = 298.2572215381; //User-defined

            static double Flattening => 1 / InverseFlattening;
            
            static double SemiMinor => SemiMajor * (1 - Flattening);

            static double Eccentricity => Math.Sqrt(1 - Math.Pow(SemiMinor, 2) / Math.Pow(SemiMajor, 2));

            public static void Convert(double x, double y, double z, out double lat, out double lon, out double hgt)
            {
                double latRad = GetLatitudeRad(x, y, z);
                double lonRad = GetLongitudeRad(x, y);
                double height = GetHeight(latRad, x, y, z);
                
                hgt = height;
                lon = (180.0 / Math.PI) * lonRad;
                lat = (180.0 / Math.PI) * latRad;
            }


            static double GetHeight(double latRad, double x, double y, double z)
            {
                double h = 0.0;
                double e2 = Math.Pow(Eccentricity, 2);
                double sinLat = Math.Sin(latRad);
                double n = GetN(SemiMajor, e2, sinLat);
                double rootx2y2 = Math.Sqrt(Math.Pow(x, 2) + Math.Pow(y, 2));

                if (Math.Abs(latRad) <= (Math.PI / 4))
                {
                    h = rootx2y2 / Math.Cos(latRad) - n;
                }
                else
                {
                    h = z / sinLat - n * (1 - e2);
                }

                return h;
            }

            static double GetLongitudeRad(double x, double y)
            {
                double longRadian = Math.Atan2(y, x);
                return longRadian;
            }

            static double GetLatitudeRad(double x, double y, double z)
            {
                double e2 = Math.Pow(Eccentricity, 2);
                double rootx2y2 = Math.Sqrt(Math.Pow(x, 2) + Math.Pow(y, 2));
                double zOverRootx2y2 = z / rootx2y2;
                double eSquaredOverRootx2y2 = e2 / rootx2y2;
                double geocentricLat = Math.Atan(zOverRootx2y2 / (1 - e2));
                double newLat = geocentricLat;

                for (int i = 0; i < 6; i++)
                {
                    double sinLat = Math.Sin(newLat);
                    double n = GetN(SemiMajor, e2, sinLat);
                    newLat = Math.Atan(zOverRootx2y2 + eSquaredOverRootx2y2 * n * sinLat);
                }

                return newLat;
            }

            static double GetN(double a, double e2, double sinLat)
            {
                return a / Math.Sqrt(1.0 - e2 * Math.Pow(sinLat, 2));
            }

           
        }
```


Geodetic to ECEF

```
class GeodeticToECEF
        {
            const double SemiMajor = 6378137.0; //user-defined
            const double InverseFlattening = 298.2572215381; //user-defined
            
            static double Flattening => 1.0 / InverseFlattening;

            static double SemiMinor => SemiMajor * (1 - Flattening);

            static double Eccentricity => Math.Sqrt(1.0 - Math.Pow(SemiMinor, 2) / Math.Pow(SemiMajor, 2));

            public static void Convert(double latRad, double lonRad, double height, out double x, out double y, out double z)
            {
                double e2 = Math.Pow(Eccentricity, 2);
                //double e2 = 2.0 * Flattening - (Flattening * Flattening);
                double sinLat = Math.Sin(latRad);
                double nLat = GetN(SemiMajor, e2, sinLat);

                x = (nLat + height) * Math.Cos(latRad) * Math.Cos(lonRad);
                y = (nLat + height) * Math.Cos(latRad) * Math.Sin(lonRad);
                z = ((1.0 - e2) * nLat + height) * Math.Sin(latRad);
            }

            static double GetN(double a, double e2, double sinLat)
            {
                return a / Math.Sqrt(1.0 - e2 * Math.Pow(sinLat, 2));
            }
        }
```

**Comment by Tronald** [comment]
James Clynch (the author of the document you linked) also wrote a JS conversion (albeit not very readable). Did you reference this in your conversion? Also what work needs to be done to finish your `Get_Height` functionality? If getting heights at the poles presents major challenges, I am ok with lower accuracy near circumpolar regions. The MGRS and UTM portions of this library suffer there as well as they aren't designed to be used there.

[http://www.oc.nps.edu/oc2902w/coord/geodesy.js](http://www.oc.nps.edu/oc2902w/coord/geodesy.js)

With that said, since you have worked this before would you like to contribute to the library by forking and building this functionality? I can help you with structuring it correctly.

**Comment by Tronald** [comment]
Moving to enhancement tracker.

**Comment by Tronald** [comment]
I have added the ECEF structure to the ECEF Branch, if you wish to participate in the conversion logic development feel free as your have more experience then me. If not I will get to it as time permits.

Once the logic is complete I will add the logic to the string parser.

**Comment by Tronald** [comment]
I've reopened the issue and tagged as "Help Wanted" in case anyone who is proficient with these conversions wants to jump in. I will get to eventually, but I will need to research in my free time if no one wants to jump in.

Those wishing to contribute to this feature should fork from the [ECEF Branch](https://github.com/Tronald/CoordinateSharp/tree/ECEF) as the ECEF class structure is built. Only the actual conversion algorithms need to be implemented.

**Comment by Tronald** [comment]
Conversion logic complete. Hoping to release by 1.1.4.6.

**Comment by Tronald** [comment]
Released and available via NuGet. Values tested against James Clynch JS calculator. Thanks for the help!
