### ISSUE TITLE
1.1.3.9 branch Coordinates ctor throws not implemented exception

### ISSUE THREAD

**Issue by Naphier** [Tronald/CoordinateSharp#71]
```
var eagerLoad = new EagerLoad();
eagerLoad.Cartesian = false;
eagerLoad.Celestial = false;
eagerLoad.UTM_MGRS = false;
coordinate = new Coordinate(lat, lng, eagerLoad);
```

will throw a not implemented exception at Coordinate.ECEF.cs line 20.

You must include
`eagerLoad.ECEF = false;`

**Comment by Tronald** [comment]
Ahhh crap I'm sorry. I created 1.1.3.9 off of the ECEF branch some how. It shouldn't reference any of the ECEF stuff yet. Let me recreate.

**Comment by Tronald** [comment]
The branch was recreated if you wish to refork and resubmit (sorry again). I can do it if you want since the mistakes were mine, but I just want you to get the contribution credit for the work you did. Let me know if you have any more issues.

**Comment by Naphier** [comment]
Probably best for you to do it, the changes are small enough, but I’m not going to have time for a while.

**Comment by Tronald** [comment]
Ok no problem. Once I get it published I will create a "develop" branch for the next version.

**Comment by Tronald** [comment]
1.1.3.9 is published and the [Develop Branch](https://github.com/Tronald/CoordinateSharp/tree/Develop) has been created. Thanks for your help.
