### ISSUE TITLE
Consider using flags / bitmasking enum for eagerload settings

### ISSUE THREAD

**Issue by Naphier** [Tronald/CoordinateSharp#72]
Not much of a problem when you only have 1 or 2 bools to set for eagerload settings, but as more coordinate systems get integrated it would be more concise to have flag enums. For example,
`new EagerLoadSettings(CelestialInfo | Cartesian);`

I'd be happy to pick this up over the next week or so. Just tell me what branch to work it out in.

**Comment by Tronald** [comment]
I agree that this makes more sense as the EagerLoading options are growing. Feel free to work on it. Once we get 1.1.3.9 out I will make a branch to start working in.

**Comment by Tronald** [comment]
Added to next release [Develop Branch](https://github.com/Tronald/CoordinateSharp/tree/Develop/CoordinateSharp)
