### ISSUE TITLE
Consider using Unit tests project for running tests

### ISSUE THREAD

**Issue by Naphier** [Tronald/CoordinateSharp#73]
This is a bigger task, but would would have a lot more automation available.  Would also prevent things like committing code that throws not implemented exceptions as the unit tests could be run with a pre-commit hook.
I'd be up for this but it might take me a month or so.

[edit] Also are there some sources to verify against? www.earthpoint.us can do a batch conversion which might be a good idea to build a database from that can be used to check a very wide range of coordinates.

**Comment by Tronald** [comment]
I have had to use different sources for verification as not much exists that can check SolarTimes and MGRS, etc in one spot. I essentially picked random areas a to test against in the TestProj, but having a more automated solution that can run against a database would be awesome! This is honestly outside my wheel house though so anything you do to make this work would be awesome!

If you take this on (which would be amazing) just let me know what you need from me and I will help where I can.

**Comment by Naphier** [comment]
The celestial conversions are pretty difficult. The MGRS I think we can
rely on earthpoint.us
They have a lot of systems they convert to. They're site is written with
asp, so I wonder if they'd be willing to contribute. I might try connecting
with them.

**Comment by Tronald** [comment]
Updating the testing methods in v2.1.1.1. There are no plans to implement webhooks at this time. That may change in the future after the ownership in transferred however.
