### ISSUE TITLE
EagerLoadType enums not working in EagerLoad constructor

### ISSUE THREAD

**Issue by parkerdj98** [Tronald/CoordinateSharp#81]
The ability to pass enum flags to the EagerLoading constructor doesn't seem to work in all cases.  When I try doing "EagerLoad eagerLoad = new EagerLoad(EagerLoadType.UTM_MGRS);", the UTM_MGRS property is still set to false.  I have to manually set the property to true by doing "eagerLoad.UTM_MGRS = true;".

Also, the examples you provide in the Developers Guide/Eager Loading section don't appear to work either.  Those examples attempt to set the EagerLoadType.Celestial and EagerLoadType.Cartesian properties to true, which does happen, but the UTM_MGRS property is also set to true but, it should be set to false.

**Comment by Tronald** [comment]
Thank you for bringing this to my attention. I was able to find the issue. Not sure why my tests didn't catch it, so i will need to look into that as well. I will push an update here and to Nuget for you this afternoon. 

Is your workaround sufficient for the time being, or do you need any help creating one?

**Comment by parkerdj98** [comment]
Yes, my workaround is sufficient: I just simply use the old "new EagerLoad(false)" constructor and then manually set the property to true with "eagerLoad.UTM_MGRS = true;".

Thanks for your prompt reply.

**Comment by Tronald** [comment]
Thanks again for creating this issue! I've fixed the issue and pushed a new package to Nuget.
