### ISSUE TITLE
Wrong bearing calculated from two coordinates

### ISSUE THREAD

**Issue by alecampagna** [Tronald/CoordinateSharp#95]
**Describe the bug**
Distance bearing give wrong value

**To Reproduce**
 var distance = new Distance
(new Coordinate(45.02258, 7.63489),new Coordinate(45.02092, 7.6332));
distanza.Bearing = 324.26014003334842

**Expected behavior**
Distance 227.4m
Azimuth 215.74deg

**Environment (please complete the following information):**
 - .NET version 4.7
 - CoordinateSharp version 1.1.5.1

**Comment by Tronald** [comment]
Thank you for bringing this to my attention.

This is strange, as it's giving you the bearing as if you were passing Western hemisphere coordinates and traveling backwards. It appears to be doing it for Haversine and Vincenty calculations. I will look into this and get back to you.

**Comment by Tronald** [comment]
I found the problem, I'm not sure how it came about though. Basically the trig functions were reversing the coordinate radian values. Many of the celestial calculations that take place use negative easting values and I am wondering if something was "switched" by accident in a distance formula. Not many people use the library for this feature so it's probably just gone unnoticed. 

v2.1.1.1 will have more expanded tests to catch things like this, but I would like to release a new v1.#.#.# of this library to get a fix out. I need to do more tests to make sure the corrections resolve the issue, but I will try and get a new package out by tomorrow.

Thank you for raising this issue. I will keep it open until I release a new package and let you know when I do so.

**Comment by alecampagna** [comment]
Hi,  thank you for working on It. We are a public transport company and we've used your library to calculate position and direction on a Real time vehicle monitoring app:http://percorsieorari.gtt.to.it/das_ws/mezzi.html(In the line field insert a number from 1 to 100)After you've resolved this issue we'll switch to use again it.Thank.RegardsACAC
-------- Messaggio originale --------Da: Justin Gielski <notifications@github.com> Data: 04/05/19  20:10  (GMT+01:00) A: Tronald/CoordinateSharp <CoordinateSharp@noreply.github.com> Cc: Alessandro Campagna <alessandro.campagna@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [Tronald/CoordinateSharp] Wrong bearing calculated from two coordinates (#95) I found the problem, I'm not sure how it came about though. Basically the trig functions were reversing the coordinate radian values. Many of the celestial calculations that take place use negative easting values and I am wondering if something was "switched" by accident in a distance formula. Not many people use the library for this feature so it's probably just gone unnoticed.
v2.1.1.1 will have more expanded tests to catch things like this, but I would like to release a new v1.#.#.# of this library to get a fix out. I need to do more tests to make sure the corrections resolve the issue, but I will try and get a new package out by tomorrow.
Thank you for raising this issue. I will keep it open until I release a new package and let you know when I do so.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Tronald/CoordinateSharp/issues/95#issuecomment-489350973",
"url": "https://github.com/Tronald/CoordinateSharp/issues/95#issuecomment-489350973",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Tronald** [comment]
Good Afternoon.

I have fixed the issue and published the new package to Nuget (v.1.1.5.2). I have also created better tests for v2.1.1.1 for the distance methods to avoid future issues like this. You may confirm the fix with this [fiddle](https://dotnetfiddle.net/snu4Pl). 

Thank you again for bringing this to my attention. Let me know if you find any other issues.

-Justin
