### ISSUE TITLE
TryParse not working with certain Cultural Settings

### ISSUE THREAD

**Issue by Petje1972** [Tronald/CoordinateSharp#97]
Hi Tronald,
I have an issue using CoordinateSharp. My goal is to convert WGS coordinate to a different formattype.
The package is used in a Xamarin.Android project and works great in debug environment but when I deploy to apk and install on a phone, the TryParse does not seem to work.
Could you give me a hint what I am doing wrong?

The used code is:
`string s = "N51° 12.768 E5° 43.849";
if(Coordinate.TryParse(s, out Coordinate c))
{

}`

This issue occurs when phone is set to Dutch language, after switching to English US the conversion works.

Thanks in advance
Patrick Vossen

**Comment by Tronald** [comment]
Hi there, thank you for checking out CoordinateSharp.

The coordinate string is parsable (as evident in your debug environment) so I am unsure why it wouldn’t parse after deployment. The only thing that sticks out to me is your ‘TryParse’ call should be producing an error in a normal environment. Normally, you cannot create your object within the ‘TryParse’ call (unless this a new C# feature I just am unaware of). I wonder if that’s what’s throwing it off.

Try this code instead.

```C#
string s = "N51° 12.768 E5° 43.849";
Coordinate c;
if(Coordinate.TryParse(s, out c))
{

}
```

If your code is compiling and working in debug this may not work. If it does work can you answer the following?

-Are you receiving any exceptions?
-Can you parse signed Coordinate “0, 0”
-Can you create a normal Coordinate object without error ‘Coordinate c = new Coordinate;’

**Comment by Tronald** [comment]
Can you parse in Dutch if you remove the degree symbols from your string?

**Comment by Petje1972** [comment]
Hi Tronald,
Thanks 4 the quick response.

Removing degree from string does not solve the issue.
Also changing dot to comma doesnot solve. (in the Netherlands the comma is used as decimal seperator instead of the dot)
I have tested with N51.211191 E005.730156 and N51,211191 E005,730156.
Both these coordinates do not work, when I switch to English US, both of them do work.

This afternoon i got some spare time, I will download your code and gonna test in debug environment to see were exactly the issue occurs.

I will get back to it.

Grtz Patrick

**Comment by Petje1972** [comment]
Hi Tronald,

I have debugged the code and it fails when the decimal separator of the system is set to comma.
When I test it with the following coordinate N 51.213º E 005.731º
It fails in the function :

private static bool TryDecimalDegree(string s, out double[] d)

In this function you convert a string to a double where, in the string the decimal seperator is a dot.
The string value of 51.213 will be converted to a double value of 51213 instead of 51.213


code where it goes wrong:
===================
if (!double.TryParse(sA[0], out lat))
{ return false; }
if (!double.TryParse(sA[1], out lng))
{ return false; }
===================

Is this something that you are going to resolve in a future version?

Best regards
Grtz Patrick

**Comment by Tronald** [comment]
Thank you for taking the time to debug this.

I was able to replicate as well by setting my thread culture to Netherlands in the test program.

`Thread.CurrentThread.CurrentCulture = new CultureInfo("nl");`

So a couple of things. The library was not built with culture in mind (as you can see). The rabbit hole goes deeper then just the `TryDecimalDegree` call I'm afraid, so I will need to brainstorm the best way to handle this. My first thought was to set the library's thread culture to en-US, but this could have undesired effects as certain security features could block setting thread cultures in certain environments. Luckily, this issue should only effect the library's parsers. I am going to look into this more and come up with a solution for v2.#.#.# versions of the library.

I think the best solution may be to set the number culture within the parsers themselves to US. That way .NET will ensure the correct number format is always used regardless of the systems culture or security settings.

For now this work around could work for you.

In your programs main thread,  set the thread culture to US. This will force your program to operate under US language settings without having to change the settings of the whole phone. I know this is not the best option, but could work if you need a quick fix and your environment allows it.

```C#
using System.Globalization;
using System.Threading;

//In your apps main thread/constructor/initializer
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");

//You shouldn't need to set UI culture, but here is the code just in case.
//Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");
```

I will follow up once a solution is built. Please let me know if the above work around works for you.

Thank you again for taking the time to open this issue!

-Justin

**Comment by Petje1972** [comment]
Hi Justin,

Thanks for the solution.
Maybe the solution I used is also usable for you.
I have extended all the TryParse in the Coordinate.Parser.cs as followed:

```
double.TryParse(sA[1], NumberStyles.Any, CultureInfo.InvariantCulture, out lng)
```
I haven't noticed any strange behavior besides when I get the coordinate `c.ToString()`, the coordinate is printed (on a Dutch system) with comma's instead of dots (obviously).
Also the current code does not accept a WGS84 coordinate with comma's, these are replaced by spaces in the package but that is no problem, now a comma used as separation between N/E is not causing a problem.

Grtz Patrick

**Comment by Tronald** [comment]
Too funny, I was just trying out your provided solution in the code as well! It looks like we think the same way. 

So far it looks good to me too, but it does break some of my tests, because the Dutch formatted string does not match the Invariant formatted string (as you specified). This is fine though. I want to add cultural changes to the tests anyway so I will address that as well.

Thanks for the help on this. Fixing this should really help expand the library!

**Comment by Tronald** [comment]
This ended up being super easy. The part of the test that was failing was simply the part that compared the to Parsed coordinate string to the Expected coordinate string do to the culture format change. I just changed the test logic to ignore periods and commas, as I am more concerned with the numeric and position values themselves within the string.

I will push this fix with v2.1.1.1.

Out of curiosity, what are you using the library for?

Thank you again for the help.

**Comment by Petje1972** [comment]
Hi Justin,

My wife does a lot of geocaching, where, on a regular base, she has to convert RD (Dutch grid) to WGS84 and vice versa.
I have build her an Android app where she easily can convert this, I am using CoordinateSharp to convert between the 3 WGS84 format types.
This app will not be available in Playstore.

FYI, the code to convert RD>>WGS84 / WGS84>>RD can be found [here](https://www.roelvanlisdonk.nl/2012/11/21/simple-way-for-converting-rijksdriehoek-coordinates-to-lat-and-long-wgs84-in-c/)

Grtz Patrick

**Comment by Tronald** [comment]
Very cool, thank you for sharing. I love when the library is used for stuff like that! I also appreciate the provided code example. I will look into adding the conversions to the code base.

Best regards

-Justin

**Comment by Petje1972** [comment]
👍
