### ISSUE TITLE
Coordinate Move changes calling object

### ISSUE THREAD

**Issue by FalcoGer** [Tronald/CoordinateSharp#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tronald** [comment]
Hi there, thanks for checking out the library. I think you may have accidentally posted this issue before finishing it? Can you review and update the issue as it looks like you posted the template.

**Comment by Tronald** [comment]
Issue never clarified. Will reopen if clarified.
