### ISSUE TITLE
Function to return the compass bearing from one point to another

### ISSUE THREAD

**Issue by FalcoGer** [Tronald/CoordinateSharp#99]
**Is your feature request related to a problem? Please describe.**
I know there is the Distance class that includes a bearing, but it'd be nice if you could get the beaing from one point to another.

**Describe the solution you'd like**
```C#
Coordinate c1;
Coordinate c2;

double compassBearing = c1.GetBearing(c2);
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tronald** [comment]
Hi, I just saw you opened and closed the issue. Did you figure out a solution to this? If not let me know and I can help you, as the library does possess that capability (in a roundabout way) to get the bearing to another coordinate. 

It may not be a bad idea to add the prescribed function for simplicity sake though. Thanks for the suggestion.
